INFO = {
    "status": 200,
    "id": 1,
    "title": "Gakuen de Jikan yo Tomare – Episode 1",
    "thumbnail": "https://btn.hitomi.la/webpbigtn/3/b2/7c731d3025aecf74205b1b188c36d65c124ca5bc0a2e81edcf28125aa9df5b23.webp",
    "artist": [],
    "group": [],
    "type": "anime",
    "language": "english",
    "series": [],
    "character": [],
    "tags": [
        "female:ahegao",
        "female:big_breasts",
        "female:blowjob",
        "female:bukkake",
        "female:defloration",
        "female:mind_break",
        "female:mind_control",
        "female:nakadashi",
        "female:rape",
        "female:schoolgirl",
        "female:x-ray",
        "tag:ffm_threesome",
        "tag:incest",
    ],
    "date": "2015-05-30 15:02:56-05",
}


IMAGE = {
    "status": 200,
    "files": [
        {
            "name": "01.png",
            "url": "https://ba.hitomi.la/webp/1650243601/946/7c731d3025aecf74205b1b188c36d65c124ca5bc0a2e81edcf28125aa9df5b23.webp",
        },
        {
            "name": "03.png",
            "url": "https://aa.hitomi.la/webp/1650243601/2737/425e9117294c1c5acb295e95e35e9e5433ac73cb01300b849f5f69b42ca50b1a.webp",
        },
    ],
}


SEARCH = {
    "status": 200,
    "result": [
        {
            "id": 1613730,
            "title": "Sekigahara-san wa Dasaretai | 세키가하라는 발산하고싶어",
            "thumbnail": "https://atn.hitomi.la/webpbigtn/2/1d/e8792b2ba4597a63d2ec69247f3bf5193ab33a8572699f47095c91695cbcb1d2.webp",
            "artist": ["tsukako"],
            "group": [],
            "type": "manga",
            "language": "korean",
            "series": [],
            "character": [],
            "tags": [
                "female:ahegao",
                "female:big_breasts",
                "female:defloration",
                "female:leg_lock",
                "female:lingerie",
                "female:nakadashi",
                "female:paizuri",
                "female:ponytail",
                "female:sole_female",
                "female:sweating",
                "male:sole_male",
                "male:sweating",
                "male:virginity",
            ],
            "date": "2020-04-16 12:13:00-05",
        },
        {
            "id": 1570712,
            "title": "Sekigahara-san wa Tasshitai | 세키가하라는 닿고싶어",
            "thumbnail": "https://btn.hitomi.la/webpbigtn/5/6c/0d2ee87048646232b205bdf1da11240542178c0c58473beb40461aa51d6ee6c5.webp",
            "artist": ["tsukako"],
            "group": [],
            "type": "manga",
            "language": "korean",
            "series": [],
            "character": [],
            "tags": [
                "female:big_breasts",
                "female:exhibitionism",
                "female:hidden_sex",
                "female:kissing",
                "female:lingerie",
                "female:masturbation",
                "female:sole_female",
                "female:sumata",
                "female:sweating",
                "male:sole_male",
                "tag:no_penetration",
            ],
            "date": "2020-02-14 07:57:00-06",
        },
        {
            "id": 1536576,
            "title": "Sekigahara-san wa Kakushitai | 세키가하라는 숨기고싶어",
            "thumbnail": "https://atn.hitomi.la/webpbigtn/d/2c/85663460c1789a1c9dcd79f8e3f00cdfcf50c5c8248135457006f54a74fdc2cd.webp",
            "artist": ["tsukako"],
            "group": [],
            "type": "manga",
            "language": "korean",
            "series": [],
            "character": [],
            "tags": [
                "female:big_breasts",
                "female:blackmail",
                "female:blowjob",
                "female:breast_feeding",
                "female:bunny_girl",
                "female:exhibitionism",
                "female:fishnets",
                "female:kemonomimi",
                "female:leotard",
                "female:paizuri",
                "female:sole_female",
                "female:sweating",
                "male:sole_male",
                "tag:no_penetration",
            ],
            "date": "2019-12-19 08:23:00-06",
        },
    ],
    "count": 3,
}
